Bump to 1.28 k8s version
rancher/csp-adapter pull request #79
Opened 2024-02-16 19:06 UTC by guangyee

Cherry-pick from 59f2e29f298f7d2f4973b4b3ada0816a5f084ae9

2024-02-16 19:24 UTC, mbelur requested changes
support matrix for v2.8.x - https://www.suse.com/suse-rancher/support-matrix/all-supported-versions/rancher-v2-8-1/ shows 1.25 as the lowest supported version.. we can update this.

2024-02-16 21:12 UTC, guangyee commented
> support matrix for v2.8.x - https://www.suse.com/suse-rancher/support-matrix/all-supported-versions/rancher-v2-8-1/ shows 1.25 as the lowest supported version.. we can update this.

Good point! I was trying to follow https://github.com/rancher/rancher/issues/43729. I don't see any other charts that raised the minimum version though.

2024-02-20 21:15 UTC, mbelur commented
> > support matrix for v2.8.x - https://www.suse.com/suse-rancher/support-matrix/all-supported-versions/rancher-v2-8-1/ shows 1.25 as the lowest supported version.. we can update this.
> 
> Good point! I was trying to follow [rancher/rancher#43729](https://github.com/rancher/rancher/issues/43729). I don't see any other charts that raised the minimum version though.

ok agreed. Let's stick with the current min version.

2024-02-20 21:16 UTC, mbelur approved these changes

2024-02-20 22:56 UTC, chajain approved these changes

2024-02-20 23:35 UTC, merged